"use strict";

import * as Color from "../constants/color.js";
import * as Label from "../constants/label.js";

const boundaryLayout = {
  "line-join": "round",
  "line-cap": "round",
  "line-sort-key": ["*", -1, ["get", "admin_level"]],
  visibility: "visible",
};

export const boundaryCasing = {
  id: "boundary_casing",
  type: "line",
  paint: {
    "line-color": [
      "interpolate",
      ["linear"],
      ["zoom"],
      2,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorderCasing - 30}, 35%, 86%)`,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        `hsl(${Color.hueBorderCasing - 30}, 25%, 94%)`,
        Color.borderCasing,
      ],
      7,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorderCasing}, 35%, 86%)`,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        `hsl(${Color.hueBorderCasing}, 30%, 90%)`,
        Color.borderCasing,
      ],
    ],
    "line-opacity": [
      "interpolate",
      ["linear"],
      ["zoom"],
      0,
      ["case", ["==", ["get", "admin_level"], 2], 0.4, 1],
      4,
      ["case", ["==", ["get", "admin_level"], 2], 1, 1],
    ],
    "line-width": [
      "interpolate",
      ["exponential", 1.2],
      ["zoom"],
      2,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        4,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 6],
        0,
        0,
      ],
      3,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        4.8,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        4,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 6],
        0,
        0,
      ],
      8,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        12,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        9.7,
        ["==", ["get", "admin_level"], 5],
        5,
        ["==", ["get", "admin_level"], 6],
        0,
        0,
      ],
      9,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        14.5,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        11.6,
        ["==", ["get", "admin_level"], 5],
        6,
        ["==", ["get", "admin_level"], 6],
        0,
        0,
      ],
      11,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        20.8,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        16.7,
        ["==", ["get", "admin_level"], 5],
        6,
        ["==", ["get", "admin_level"], 6],
        5,
        0,
      ],
      12,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        25,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        20,
        ["==", ["get", "admin_level"], 5],
        6,
        ["==", ["get", "admin_level"], 6],
        6,
        0,
      ],
      16,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        50,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        30,
        ["==", ["get", "admin_level"], 5],
        6,
        ["==", ["get", "admin_level"], 6],
        6,
        0,
      ],
    ],
  },
  filter: [
    "all",
    ["in", ["get", "admin_level"], ["literal", [2, 3, 4, 5, 6]]],
    ["==", ["get", "maritime"], 0],
  ],
  minzoom: 2,
  layout: boundaryLayout,
  source: "openmaptiles",
  "source-layer": "boundary",
};

export const administrative = {
  id: "boundary_administrative",
  type: "line",
  paint: {
    "line-color": [
      "step",
      ["zoom"],
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        ["==", ["get", "admin_level"], 3],
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        ["==", ["get", "admin_level"], 4],
        `hsl(${Color.hueBorder}, 2%, 60%)`,
        Color.border,
      ],
      3,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        ["==", ["get", "admin_level"], 3],
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        ["==", ["get", "admin_level"], 4],
        `hsl(${Color.hueBorder}, 2%, 60%)`,
        Color.border,
      ],
      5,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorder}, 2%, 42.2%)`,
        ["==", ["get", "admin_level"], 3],
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        ["==", ["get", "admin_level"], 4],
        `hsl(${Color.hueBorder}, 2%, 54.3%)`,
        Color.border,
      ],
      7,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        `hsl(${Color.hueBorder}, 2%, 37%)`,
        ["==", ["get", "admin_level"], 3],
        `hsl(${Color.hueBorder}, 2%, 37%)`,
        ["==", ["get", "admin_level"], 4],
        `hsl(${Color.hueBorder}, 2%, 48%)`,
        Color.border,
      ],
    ],
    "line-dasharray": [
      "step",
      ["zoom"],
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        ["literal", [1000, 0]],
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        ["literal", [4, 4, 4, 4, 12, 4]],
        ["==", ["get", "admin_level"], 5],
        ["literal", [5, 4]],
        ["==", ["get", "admin_level"], 6],
        ["literal", [3, 3]],
        ["literal", [2, 4]],
      ],
      3,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        ["literal", [10, 1, 3, 1]],
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        ["literal", [4, 4, 4, 4, 12, 4]],
        ["==", ["get", "admin_level"], 5],
        ["literal", [5, 4]],
        ["==", ["get", "admin_level"], 6],
        ["literal", [3, 3]],
        ["literal", [2, 4]],
      ],
      6,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        ["literal", [10, 1, 3, 1]],
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        ["literal", [3.5, 3, 3.5, 3, 20, 3]],
        ["==", ["get", "admin_level"], 5],
        ["literal", [5, 4]],
        ["==", ["get", "admin_level"], 6],
        ["literal", [3, 3]],
        ["literal", [2, 4]],
      ],
      8,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        ["literal", [10, 1, 3, 1]],
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        ["literal", [2.5, 2.5, 2.5, 2.5, 20, 2.5]],
        ["==", ["get", "admin_level"], 5],
        ["literal", [5, 4]],
        ["==", ["get", "admin_level"], 6],
        ["literal", [3, 3]],
        ["literal", [2, 4]],
      ],
      10,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        ["literal", [10, 1, 3, 1]],
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        ["literal", [2, 2.5, 2, 2.5, 12, 2.5]],
        ["==", ["get", "admin_level"], 5],
        ["literal", [5, 4]],
        ["==", ["get", "admin_level"], 6],
        ["literal", [3, 3]],
        ["literal", [2, 4]],
      ],
    ],
    "line-opacity": [
      "step",
      ["zoom"],
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        0.4,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 8],
        0,
        1,
      ],
      3,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        0.85,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 8],
        0,
        1,
      ],
      4,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 8],
        0,
        1,
      ],
      5,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        0.8,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1,
        ["==", ["get", "admin_level"], 5],
        0,
        ["==", ["get", "admin_level"], 8],
        0,
        1,
      ],
      6,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        0.8,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1,
        ["==", ["get", "admin_level"], 5],
        1,
        ["==", ["get", "admin_level"], 8],
        0,
        1,
      ],
      11,
      1,
    ],
    "line-width": [
      "step",
      ["zoom"],
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0.5,
        1,
      ],
      2,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0.5,
        1,
      ],
      3,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0.5,
        1,
      ],
      4,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1.5,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0.5,
        1,
      ],
      5,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1.5,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        0.8,
        1,
      ],
      7,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        1.5,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1.1,
        1,
      ],
      10,
      [
        "case",
        ["==", ["get", "admin_level"], 2],
        2.3,
        ["in", ["get", "admin_level"], ["literal", [3, 4]]],
        1.5,
        1,
      ],
    ],
    "line-offset": 0,
    "line-blur": 0,
  },
  filter: [
    "all",
    ["==", ["get", "disputed"], 0],
    [
      "case",
      ["==", ["get", "admin_level"], 2],
      [
        "any",
        ["==", ["get", "maritime"], 0],
        ["all", ["has", "adm0_l"], ["has", "adm0_r"]],
      ],
      ["==", ["get", "maritime"], 0],
    ],
    ["in", ["get", "admin_level"], ["literal", [2, 3, 4, 5, 6, 8]]],
  ],
  minzoom: 0,
  maxzoom: 24,
  layout: boundaryLayout,
  source: "openmaptiles",
  "source-layer": "boundary",
};

// adm0_* properties are only available on international borders.
const maritime = [
  "any",
  ["==", ["get", "maritime"], 0],
  ["all", ["has", "adm0_l"], ["has", "adm0_r"]],
];

/**
 * Returns an expression that converts the given country code to a
 * human-readable name in the user's preferred language.
 *
 * @param code An expression that evaluates to an ISO 3166-1 alpha-3 country
 *  code.
 */
function getCountryName(code) {
  return [
    "let",
    "code",
    code,
    "countryNamesByCode",
    ["literal", Label.countryNamesByCode],
    [
      "coalesce",
      ["get", ["var", "code"], ["var", "countryNamesByCode"]],
      // Fall back to the country code in parentheses.
      ["concat", "(", ["var", "code"], ")"],
    ],
  ];
}

export const countryLabelLeft = {
  id: "boundary_country_label_left",
  type: "symbol",
  paint: {
    "text-color": {
      base: 1.2,
      stops: [
        [3, `hsl(${Color.hueBorder}, 2%, 24%)`],
        [7, `hsl(${Color.hueBorder}, 2%, 18%)`],
      ],
    },
  },
  layout: {
    "symbol-placement": "line",
    "text-font": ["Americana-Bold"],
    "text-size": {
      stops: [
        [3, 6],
        [7, 10],
      ],
    },
    "text-field": getCountryName(["get", "adm0_l"]),
    "text-offset": [0, -1],
    "text-max-angle": 30,
    "text-letter-spacing": 0.1,
    "text-ignore-placement": true,
  },
  filter: [...maritime],
  maxzoom: 24,
  source: "openmaptiles",
  "source-layer": "boundary",
};

export const countryLabelRight = {
  ...countryLabelLeft,
  id: "boundary_country_label_right",
  layout: {
    ...countryLabelLeft.layout,
    "text-field": getCountryName(["get", "adm0_r"]),
    "text-offset": [0, 1],
  },
};

export const legendEntries = [
  {
    description: "Country or dependency",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 2],
  },
  {
    description: "State or province",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 4],
  },
  {
    description: "Region",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 5],
  },
  {
    description: "County or county-equivalent",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 6],
  },
  {
    description: "City, town, or village",
    layers: [boundaryCasing.id],
    filter: ["in", ["get", "admin_level"], ["literal", [7, 8, 9]]],
  },
  {
    description: "Disputed border",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "disputed"], 1],
  },
];
