"use strict";

import * as Color from "../constants/color.js";
import * as Label from "../constants/label.js";

const boundaryLayout = {
  "line-join": "round",
  "line-cap": "round",
  "line-sort-key": ["*", -1, ["get", "admin_level"]],
  visibility: "visible",
};

export const boundaryCasing = {
  id: "boundary_casing",
  type: "line",
  paint: {
    "line-color": [
      "interpolate",
      ["linear"],
      ["zoom"],
      2,
      [
        "match",
        ["get", "admin_level"],
        2,
        `hsl(${Color.hueBorderCasing - 30}, 35%, 86%)`,
        3,
        `hsl(${Color.hueBorderCasing - 30}, 25%, 94%)`,
        4,
        `hsl(${Color.hueBorderCasing - 30}, 25%, 94%)`,
        /* else */ Color.borderCasing,
      ],
      7,
      [
        "match",
        ["get", "admin_level"],
        2,
        `hsl(${Color.hueBorderCasing}, 35%, 86%)`,
        3,
        `hsl(${Color.hueBorderCasing}, 30%, 90%)`,
        4,
        `hsl(${Color.hueBorderCasing}, 30%, 90%)`,
        /* else */ Color.borderCasing,
      ],
    ],
    "line-opacity": [
      "interpolate",
      ["linear"],
      ["zoom"],
      0,
      ["match", ["get", "admin_level"], 2, 0.4, /* else */ 1],
      4,
      1,
    ],
    "line-width": [
      "interpolate",
      ["exponential", 1.2],
      ["zoom"],
      2,
      ["match", ["get", "admin_level"], 2, 4, /* else */ 0],
      3,
      ["match", ["get", "admin_level"], 2, 8.1, 3, 4, 4, 4, /* else */ 0],
      8,
      [
        "match",
        ["get", "admin_level"],
        2,
        14.1,
        3,
        11.7,
        4,
        11.7,
        5,
        5,
        /* else */ 0,
      ],
      9,
      [
        "match",
        ["get", "admin_level"],
        2,
        16.2,
        3,
        13.3,
        4,
        13.3,
        5,
        6,
        /* else */ 0,
      ],
      10,
      [
        "match",
        ["get", "admin_level"],
        2,
        18.6,
        3,
        15.1,
        4,
        15.1,
        5,
        6,
        /* else */ 0,
      ],
      11,
      [
        "match",
        ["get", "admin_level"],
        2,
        21.5,
        3,
        17.3,
        4,
        17.3,
        5,
        6,
        6,
        5,
        /* else */ 0,
      ],
      12,
      [
        "match",
        ["get", "admin_level"],
        2,
        25,
        3,
        20,
        4,
        20,
        5,
        6,
        6,
        6,
        /* else */ 0,
      ],
      16,
      [
        "match",
        ["get", "admin_level"],
        2,
        50,
        3,
        30,
        4,
        30,
        5,
        6,
        6,
        6,
        /* else */ 0,
      ],
    ],
  },
  filter: [
    "all",
    ["in", ["get", "admin_level"], ["literal", [2, 3, 4, 5, 6]]],
    ["==", ["get", "maritime"], 0],
  ],
  minzoom: 2,
  layout: boundaryLayout,
  source: "openmaptiles",
  "source-layer": "boundary",
};

export const administrative = {
  id: "boundary_administrative",
  type: "line",
  paint: {
    "line-color": [
      "interpolate",
      ["exponential", 1.2],
      ["zoom"],
      3,
      [
        "match",
        ["get", "admin_level"],
        2,
        `hsl(${Color.hueBorder}, 2%, 47%)`,
        3,
        `hsl(${Color.hueBorder}, 2%, 60%)`,
        4,
        `hsl(${Color.hueBorder}, 2%, 60%)`,
        /* else */ Color.border,
      ],
      7,
      [
        "match",
        ["get", "admin_level"],
        2,
        `hsl(${Color.hueBorder}, 2%, 37%)`,
        3,
        `hsl(${Color.hueBorder}, 2%, 48%)`,
        4,
        `hsl(${Color.hueBorder}, 2%, 48%)`,
        /* else */ Color.border,
      ],
    ],
    "line-dasharray": [
      "step",
      ["zoom"],
      ["literal", [1000, 0]],
      3,
      [
        "match",
        ["get", "admin_level"],
        2,
        ["literal", [10, 1, 3, 1]],
        3,
        ["literal", [4, 4, 4, 4, 12, 4]],
        4,
        ["literal", [4, 4, 4, 4, 12, 4]],
        5,
        ["literal", [5, 4]],
        6,
        ["literal", [3, 3]],
        /* else */ ["literal", [2, 4]],
      ],
      6,
      [
        "match",
        ["get", "admin_level"],
        3,
        ["literal", [3.5, 3, 3.5, 3, 20, 3]],
        4,
        ["literal", [3.5, 3, 3.5, 3, 20, 3]],
        /* else */ [
          "match",
          ["get", "admin_level"],
          2,
          ["literal", [10, 1, 3, 1]],
          5,
          ["literal", [5, 4]],
          6,
          ["literal", [3, 3]],
          /* else */ ["literal", [2, 4]],
        ],
      ],
      8,
      [
        "match",
        ["get", "admin_level"],
        3,
        ["literal", [2.5, 2.5, 2.5, 2.5, 20, 2.5]],
        4,
        ["literal", [2.5, 2.5, 2.5, 2.5, 20, 2.5]],
        /* else */ [
          "match",
          ["get", "admin_level"],
          2,
          ["literal", [10, 1, 3, 1]],
          5,
          ["literal", [5, 4]],
          6,
          ["literal", [3, 3]],
          /* else */ ["literal", [2, 4]],
        ],
      ],
      10,
      [
        "match",
        ["get", "admin_level"],
        3,
        ["literal", [2, 2.5, 2, 2.5, 12, 2.5]],
        4,
        ["literal", [2, 2.5, 2, 2.5, 12, 2.5]],
        /* else */ [
          "match",
          ["get", "admin_level"],
          2,
          ["literal", [10, 1, 3, 1]],
          5,
          ["literal", [5, 4]],
          6,
          ["literal", [3, 3]],
          /* else */ ["literal", [2, 4]],
        ],
      ],
      12,
      [
        "match",
        ["get", "admin_level"],
        2,
        ["literal", [10, 1, 3, 1]],
        3,
        ["literal", [2, 2.5, 2, 2.5, 12, 2.5]],
        4,
        ["literal", [2, 2.5, 2, 2.5, 12, 2.5]],
        5,
        ["literal", [5, 4]],
        6,
        ["literal", [3, 3]],
        /* else */ ["literal", [2, 4]],
      ],
    ],
    "line-opacity": [
      "interpolate",
      ["linear"],
      ["zoom"],
      0,
      [
        "match",
        ["get", "admin_level"],
        2,
        0.4,
        3,
        0,
        4,
        0,
        5,
        1,
        6,
        1,
        /* else */ 0,
      ],
      3,
      [
        "match",
        ["get", "admin_level"],
        2,
        0.85,
        3,
        1,
        4,
        1,
        5,
        1,
        6,
        1,
        /* else */ 0,
      ],
      4,
      [
        "match",
        ["get", "admin_level"],
        2,
        1,
        3,
        1,
        4,
        1,
        5,
        1,
        6,
        1,
        /* else */ 0,
      ],
      5,
      [
        "match",
        ["get", "admin_level"],
        2,
        0.8,
        3,
        1,
        4,
        1,
        5,
        1,
        6,
        1,
        /* else */ 0,
      ],
    ],
    "line-width": [
      "interpolate",
      ["linear"],
      ["zoom"],
      2,
      ["match", ["get", "admin_level"], 2, 1, /* else */ 1],
      3,
      ["match", ["get", "admin_level"], 2, 1, 3, 0.5, 4, 0.5, /* else */ 1],
      4,
      [
        "match",
        ["get", "admin_level"],
        2,
        1.5,
        3,
        0.643,
        4,
        0.643,
        /* else */ 1,
      ],
      10,
      ["match", ["get", "admin_level"], 2, 2.25, 3, 1.5, 4, 1.5, /* else */ 1],
    ],
  },
  filter: [
    "all",
    ["==", ["get", "disputed"], 0],
    [
      "match",
      ["get", "admin_level"],
      2,
      [
        "any",
        ["==", ["get", "maritime"], 0],
        ["all", ["has", "adm0_l"], ["has", "adm0_r"]],
      ],
      /* else */ ["==", ["get", "maritime"], 0],
    ],
    ["in", ["get", "admin_level"], ["literal", [2, 3, 4, 5, 6, 8]]],
  ],
  minzoom: 0,
  maxzoom: 24,
  layout: {
    ...boundaryLayout,
    "line-cap": "butt",
  },
  source: "openmaptiles",
  "source-layer": "boundary",
};

// adm0_* properties are only available on international borders.
const maritime = [
  "any",
  ["==", ["get", "maritime"], 0],
  ["all", ["has", "adm0_l"], ["has", "adm0_r"]],
];

/**
 * Returns an expression that converts the given country code to a
 * human-readable name in the user's preferred language.
 *
 * @param code An expression that evaluates to an ISO 3166-1 alpha-3 country
 *  code.
 */
function getCountryName(code) {
  return [
    "let",
    "code",
    code,
    "countryNamesByCode",
    ["literal", Label.countryNamesByCode],
    [
      "coalesce",
      ["get", ["var", "code"], ["var", "countryNamesByCode"]],
      // Fall back to the country code in parentheses.
      ["concat", "(", ["var", "code"], ")"],
    ],
  ];
}

export const countryLabelLeft = {
  id: "boundary_country_label_left",
  type: "symbol",
  paint: {
    "text-color": {
      base: 1.2,
      stops: [
        [3, `hsl(${Color.hueBorder}, 2%, 24%)`],
        [7, `hsl(${Color.hueBorder}, 2%, 18%)`],
      ],
    },
  },
  layout: {
    "symbol-placement": "line",
    "text-font": ["Americana-Bold"],
    "text-size": {
      stops: [
        [3, 6],
        [7, 10],
      ],
    },
    "text-field": getCountryName(["get", "adm0_l"]),
    "text-offset": [0, -1],
    "text-max-angle": 30,
    "text-letter-spacing": 0.1,
    "text-ignore-placement": true,
  },
  filter: [...maritime],
  maxzoom: 24,
  source: "openmaptiles",
  "source-layer": "boundary",
};

export const countryLabelRight = {
  ...countryLabelLeft,
  id: "boundary_country_label_right",
  layout: {
    ...countryLabelLeft.layout,
    "text-field": getCountryName(["get", "adm0_r"]),
    "text-offset": [0, 1],
  },
};

export const legendEntries = [
  {
    description: "Country or dependency",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 2],
  },
  {
    description: "State or province",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 4],
  },
  {
    description: "Region",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 5],
  },
  {
    description: "County or county-equivalent",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "admin_level"], 6],
  },
  {
    description: "City, town, or village",
    layers: [boundaryCasing.id],
    filter: ["in", ["get", "admin_level"], ["literal", [7, 8, 9]]],
  },
  {
    description: "Disputed border",
    layers: [boundaryCasing.id],
    filter: ["==", ["get", "disputed"], 1],
  },
];
