name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v3.3 # https://github.com/creyD/prettier_action
        with:
          dry: true
          prettier_options: --write .
          # Setting only_changed to false picks up new files
          only_changed: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
