name: Test Build (MacOS)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build Shield Library 🛡️
        run: |
          cd shieldlib
          npm ci --include=dev
          npm run build
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          npm run build
          npm run style
      - name: Test 🧪
        run: |
          npm test
          cd shieldlib
          npm test
